// Emergency bypass code verification.
//
// 52 argon2id hashes ship in bypass_table.rs. The master secret lives
// outside the repo at %USERPROFILE%\.open-choice\keys\heartbeat-bypass-master-<year>.key
// and is only used by the scripts in open-choice-heartbeat/scripts/ to
// (a) generate the table at release time and (b) derive a single week's code
// when support needs to issue one.
//
// A cracked binary yields argon2 hashes, not codes — and each hash is keyed
// to one week, so cracking one hash buys exactly one week of bypass. Rotate
// the master at each release to close future leaks.

use argon2::password_hash::PasswordHash;
use argon2::{Argon2, PasswordVerifier};
use chrono::{DateTime, Duration, Utc};
use thiserror::Error;

use crate::bypass_table::{bypass_epoch, BYPASS_TABLE};

/// How long a successful bypass extends grace.
pub const BYPASS_GRACE: Duration = Duration::days(7);

#[derive(Debug, Error)]
pub enum BypassError {
    #[error("emergency bypass is no longer available — please update Open Choice")]
    HorizonExpired,
    #[error("invalid emergency code")]
    Invalid,
    #[error("bypass table not configured (empty) — this build has no bypass codes")]
    NotConfigured,
    #[error("bypass table entry is malformed: {0}")]
    Malformed(String),
}

/// Verify a user-entered emergency code against this week's pre-shipped hash.
/// Returns the new `emergency_bypass_until` timestamp on success.
pub fn try_bypass(input: &str) -> Result<DateTime<Utc>, BypassError> {
    try_bypass_at(input, Utc::now())
}

/// Testable variant — accepts `now` as a parameter.
pub fn try_bypass_at(input: &str, now: DateTime<Utc>) -> Result<DateTime<Utc>, BypassError> {
    if BYPASS_TABLE.is_empty() {
        return Err(BypassError::NotConfigured);
    }
    let week_idx = week_index(now);
    if week_idx >= BYPASS_TABLE.len() {
        return Err(BypassError::HorizonExpired);
    }
    let trimmed = input.trim();
    if trimmed.is_empty() {
        return Err(BypassError::Invalid);
    }
    let encoded = BYPASS_TABLE[week_idx];
    let parsed = PasswordHash::new(encoded).map_err(|e| BypassError::Malformed(e.to_string()))?;
    Argon2::default()
        .verify_password(trimmed.as_bytes(), &parsed)
        .map_err(|_| BypassError::Invalid)?;
    Ok(now + BYPASS_GRACE)
}

fn week_index(now: DateTime<Utc>) -> usize {
    let epoch = bypass_epoch();
    if now < epoch {
        return 0;
    }
    let delta = now - epoch;
    (delta.num_weeks() as i64).max(0) as usize
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bypass_table::BYPASS_TABLE;

    #[test]
    fn empty_table_is_not_configured() {
        // Documents placeholder behaviour. Becomes obsolete once BYPASS_TABLE
        // is populated — which flags the transition.
        if BYPASS_TABLE.is_empty() {
            match try_bypass_at("whatever", Utc::now()) {
                Err(BypassError::NotConfigured) => {}
                other => panic!("expected NotConfigured, got {other:?}"),
            }
        }
    }

    // Fixture generated by @node-rs/argon2 with the exact params the
    // generator script ships (m=65536, t=3, p=1, Argon2id v0x13). Locks in
    // the guarantee that phc strings emitted by the Node generator verify
    // against this crate.
    const FIXTURE_CODE: &str = "H9F03AS2";
    const FIXTURE_PHC:  &str = "$argon2id$v=19$m=65536,t=3,p=1$loFoRHeSwjVC+abDdMXwrg$B+A9avMHk0rzket0xfR3i4NQeVB/coxWqujHkzhXapk";

    #[test]
    fn node_emitted_phc_verifies() {
        let parsed = PasswordHash::new(FIXTURE_PHC).expect("phc parses");
        Argon2::default()
            .verify_password(FIXTURE_CODE.as_bytes(), &parsed)
            .expect("fixture verifies");
    }

    #[test]
    fn wrong_code_fails() {
        let parsed = PasswordHash::new(FIXTURE_PHC).expect("phc parses");
        assert!(Argon2::default()
            .verify_password(b"WRONGCOD", &parsed)
            .is_err());
    }
}
